# PySNMP SMI module. Autogenerated from smidump -f python HCNUM-TC
# by libsmi2pysnmp-0.0.3-alpha at Wed Nov 10 12:10:18 2004,
# Python version (2, 2, 1, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pysnmp.asn1 import subtypes

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( Bits, Counter64, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter64", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks", "mib-2")
( TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention")

# Types

class CounterBasedGauge64(Counter64):
    pass

class ZeroBasedCounter64(Counter64):
    pass


# Objects

hcnumTC = ModuleIdentity((1, 3, 6, 1, 2, 1, 78))

# Augmentions

# Exports

# Types
mibBuilder.exportSymbols("HCNUM-TC", CounterBasedGauge64=CounterBasedGauge64, ZeroBasedCounter64=ZeroBasedCounter64)

# Objects
mibBuilder.exportSymbols("HCNUM-TC", hcnumTC=hcnumTC)

