# PySNMP SMI module. Autogenerated from smidump -f python IANA-LANGUAGE-MIB
# by libsmi2pysnmp-0.0.3-alpha at Wed Nov 10 12:10:58 2004,
# Python version (2, 2, 1, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pysnmp.asn1 import subtypes

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( Bits, Integer32, ModuleIdentity, MibIdentifier, ObjectIdentity, TimeTicks, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "ObjectIdentity", "TimeTicks", "mib-2")

# Objects

ianaLanguages = ModuleIdentity((1, 3, 6, 1, 2, 1, 73))
ianaLangJavaByteCode = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 1))
ianaLangTcl = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 2))
ianaLangPerl = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 3))
ianaLangScheme = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 4))
ianaLangSRSL = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 5))
ianaLangPSL = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 6))
ianaLangSMSL = MibIdentifier((1, 3, 6, 1, 2, 1, 73, 7))

# Augmentions

# Exports

# Objects
mibBuilder.exportSymbols("IANA-LANGUAGE-MIB", ianaLanguages=ianaLanguages, ianaLangJavaByteCode=ianaLangJavaByteCode, ianaLangTcl=ianaLangTcl, ianaLangPerl=ianaLangPerl, ianaLangScheme=ianaLangScheme, ianaLangSRSL=ianaLangSRSL, ianaLangPSL=ianaLangPSL, ianaLangSMSL=ianaLangSMSL)

