# PySNMP SMI module. Autogenerated from smidump -f python ROHC-RTP-MIB
# by libsmi2pysnmp-0.0.7-alpha at Wed Feb  7 16:13:12 2007,
# Python version (2, 4, 3, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( rohcChannelID, rohcContextCID, ) = mibBuilder.importSymbols("ROHC-MIB", "rohcChannelID", "rohcContextCID")
( ModuleCompliance, ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "ObjectGroup")
( Bits, Counter32, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "mib-2")
( TruthValue, ) = mibBuilder.importSymbols("SNMPv2-TC", "TruthValue")

# Objects

rohcRtpMIB = ModuleIdentity((1, 3, 6, 1, 2, 1, 114)).setRevisions(("2004-06-03 00:00",))
rohcRtpObjects = MibIdentifier((1, 3, 6, 1, 2, 1, 114, 1))
rohcRtpContextTable = MibTable((1, 3, 6, 1, 2, 1, 114, 1, 1))
rohcRtpContextEntry = MibTableRow((1, 3, 6, 1, 2, 1, 114, 1, 1, 1)).setIndexNames((0, "ROHC-MIB", "rohcChannelID"), (0, "ROHC-MIB", "rohcContextCID"))
rohcRtpContextState = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 3), Integer().subtype(subtypeSpec=constraint.SingleValueConstraint(5,3,4,2,1,6,)).subtype(namedValues=namedval.NamedValues(("initAndRefresh", 1), ("firstOrder", 2), ("secondOrder", 3), ("noContext", 4), ("staticContext", 5), ("fullContext", 6), ))).setMaxAccess("readonly")
rohcRtpContextMode = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 4), Integer().subtype(subtypeSpec=constraint.SingleValueConstraint(3,1,2,)).subtype(namedValues=namedval.NamedValues(("unidirectional", 1), ("optimistic", 2), ("reliable", 3), ))).setMaxAccess("readonly")
rohcRtpContextAlwaysPad = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 5), TruthValue().clone('false')).setMaxAccess("readonly")
rohcRtpContextLargePktsAllowed = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 6), TruthValue().clone('true')).setMaxAccess("readonly")
rohcRtpContextVerifyPeriod = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 7), Unsigned32().clone(0)).setMaxAccess("readonly")
rohcRtpContextSizesAllowed = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 8), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 4294967295L))).setMaxAccess("readonly")
rohcRtpContextSizesUsed = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 9), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 4294967295L))).setMaxAccess("readonly")
rohcRtpContextACKs = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 10), Counter32()).setMaxAccess("readonly")
rohcRtpContextNACKs = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 11), Counter32()).setMaxAccess("readonly")
rohcRtpContextSNACKs = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 12), Counter32()).setMaxAccess("readonly")
rohcRtpContextNHPs = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 13), Counter32()).setMaxAccess("readonly")
rohcRtpContextCSPs = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 14), Counter32()).setMaxAccess("readonly")
rohcRtpContextCCPs = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 15), Counter32()).setMaxAccess("readonly")
rohcRtpContextPktsLostPhysical = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 16), Counter32()).setMaxAccess("readonly")
rohcRtpContextPktsLostPreLink = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 1, 1, 17), Counter32()).setMaxAccess("readonly")
rohcRtpPacketSizeTable = MibTable((1, 3, 6, 1, 2, 1, 114, 1, 2))
rohcRtpPacketSizeEntry = MibTableRow((1, 3, 6, 1, 2, 1, 114, 1, 2, 1)).setIndexNames((0, "ROHC-MIB", "rohcChannelID"), (0, "ROHC-MIB", "rohcContextCID"), (0, "ROHC-RTP-MIB", "rohcRtpPacketSize"))
rohcRtpPacketSize = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 2, 1, 3), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 4294967295L))).setMaxAccess("noaccess")
rohcRtpPacketSizePreferred = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 2, 1, 4), TruthValue()).setMaxAccess("readonly")
rohcRtpPacketSizeUsed = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 2, 1, 5), TruthValue()).setMaxAccess("readonly")
rohcRtpPacketSizeRestrictedType = MibTableColumn((1, 3, 6, 1, 2, 1, 114, 1, 2, 1, 6), Integer().subtype(subtypeSpec=constraint.SingleValueConstraint(2,1,3,)).subtype(namedValues=namedval.NamedValues(("nhpOnly", 1), ("rhpOnly", 2), ("noRestrictions", 3), ))).setMaxAccess("readonly")
rohcRtpConformance = MibIdentifier((1, 3, 6, 1, 2, 1, 114, 2))
rohcRtpCompliances = MibIdentifier((1, 3, 6, 1, 2, 1, 114, 2, 1))
rohcRtpGroups = MibIdentifier((1, 3, 6, 1, 2, 1, 114, 2, 2))

# Augmentions

# Groups

rohcRtpStatisticsGroup = ObjectGroup((1, 3, 6, 1, 2, 1, 114, 2, 2, 3)).setObjects(("ROHC-RTP-MIB", "rohcRtpContextSNACKs"), ("ROHC-RTP-MIB", "rohcRtpContextNHPs"), ("ROHC-RTP-MIB", "rohcRtpContextCSPs"), ("ROHC-RTP-MIB", "rohcRtpContextPktsLostPreLink"), ("ROHC-RTP-MIB", "rohcRtpContextNACKs"), ("ROHC-RTP-MIB", "rohcRtpContextCCPs"), ("ROHC-RTP-MIB", "rohcRtpContextACKs"), ("ROHC-RTP-MIB", "rohcRtpContextPktsLostPhysical"), )
rohcRtpPacketSizesGroup = ObjectGroup((1, 3, 6, 1, 2, 1, 114, 2, 2, 2)).setObjects(("ROHC-RTP-MIB", "rohcRtpContextSizesUsed"), ("ROHC-RTP-MIB", "rohcRtpPacketSizeRestrictedType"), ("ROHC-RTP-MIB", "rohcRtpPacketSizePreferred"), ("ROHC-RTP-MIB", "rohcRtpContextSizesAllowed"), ("ROHC-RTP-MIB", "rohcRtpPacketSizeUsed"), )
rohcRtpContextGroup = ObjectGroup((1, 3, 6, 1, 2, 1, 114, 2, 2, 1)).setObjects(("ROHC-RTP-MIB", "rohcRtpContextVerifyPeriod"), ("ROHC-RTP-MIB", "rohcRtpContextLargePktsAllowed"), ("ROHC-RTP-MIB", "rohcRtpContextAlwaysPad"), ("ROHC-RTP-MIB", "rohcRtpContextMode"), ("ROHC-RTP-MIB", "rohcRtpContextState"), )

# Exports

# Module identity
mibBuilder.exportSymbols("ROHC-RTP-MIB", PYSNMP_MODULE_ID=rohcRtpMIB)

# Objects
mibBuilder.exportSymbols("ROHC-RTP-MIB", rohcRtpMIB=rohcRtpMIB, rohcRtpObjects=rohcRtpObjects, rohcRtpContextTable=rohcRtpContextTable, rohcRtpContextEntry=rohcRtpContextEntry, rohcRtpContextState=rohcRtpContextState, rohcRtpContextMode=rohcRtpContextMode, rohcRtpContextAlwaysPad=rohcRtpContextAlwaysPad, rohcRtpContextLargePktsAllowed=rohcRtpContextLargePktsAllowed, rohcRtpContextVerifyPeriod=rohcRtpContextVerifyPeriod, rohcRtpContextSizesAllowed=rohcRtpContextSizesAllowed, rohcRtpContextSizesUsed=rohcRtpContextSizesUsed, rohcRtpContextACKs=rohcRtpContextACKs, rohcRtpContextNACKs=rohcRtpContextNACKs, rohcRtpContextSNACKs=rohcRtpContextSNACKs, rohcRtpContextNHPs=rohcRtpContextNHPs, rohcRtpContextCSPs=rohcRtpContextCSPs, rohcRtpContextCCPs=rohcRtpContextCCPs, rohcRtpContextPktsLostPhysical=rohcRtpContextPktsLostPhysical, rohcRtpContextPktsLostPreLink=rohcRtpContextPktsLostPreLink, rohcRtpPacketSizeTable=rohcRtpPacketSizeTable, rohcRtpPacketSizeEntry=rohcRtpPacketSizeEntry, rohcRtpPacketSize=rohcRtpPacketSize, rohcRtpPacketSizePreferred=rohcRtpPacketSizePreferred, rohcRtpPacketSizeUsed=rohcRtpPacketSizeUsed, rohcRtpPacketSizeRestrictedType=rohcRtpPacketSizeRestrictedType, rohcRtpConformance=rohcRtpConformance, rohcRtpCompliances=rohcRtpCompliances, rohcRtpGroups=rohcRtpGroups)

# Groups
mibBuilder.exportSymbols("ROHC-RTP-MIB", rohcRtpStatisticsGroup=rohcRtpStatisticsGroup, rohcRtpPacketSizesGroup=rohcRtpPacketSizesGroup, rohcRtpContextGroup=rohcRtpContextGroup)
