# PySNMP SMI module. Autogenerated from smidump -f python SFLOW-MIB
# by libsmi2pysnmp-0.0.5-alpha at Fri Oct 28 00:30:52 2005,
# Python version (2, 4, 0, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( InetAddress, InetAddressType, ) = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddress", "InetAddressType")
( OwnerString, ) = mibBuilder.importSymbols("RMON-MIB", "OwnerString")
( SnmpAdminString, ) = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
( ModuleCompliance, ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "ObjectGroup")
( Bits, Integer32, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "enterprises")

# Objects

sFlowMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 4300, 1))
sFlowAgent = MibIdentifier((1, 3, 6, 1, 4, 1, 4300, 1, 1))
sFlowVersion = MibScalar((1, 3, 6, 1, 4, 1, 4300, 1, 1, 1), SnmpAdminString()).setMaxAccess("readonly")
sFlowAgentAddressType = MibScalar((1, 3, 6, 1, 4, 1, 4300, 1, 1, 2), InetAddressType()).setMaxAccess("readonly")
sFlowAgentAddress = MibScalar((1, 3, 6, 1, 4, 1, 4300, 1, 1, 3), InetAddress()).setMaxAccess("readonly")
sFlowTable = MibTable((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4))
sFlowEntry = MibTableRow((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1)).setIndexNames((0, "SFLOW-MIB", "sFlowDataSource"))
sFlowDataSource = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 1), ObjectIdentifier()).setMaxAccess("readonly")
sFlowOwner = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 2), OwnerString()).setMaxAccess("readwrite")
sFlowTimeout = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 3), Integer32().clone(0)).setMaxAccess("readwrite")
sFlowPacketSamplingRate = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 4), Integer32().clone(0)).setMaxAccess("readwrite")
sFlowCounterSamplingInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 5), Integer32().clone(0)).setMaxAccess("readwrite")
sFlowMaximumHeaderSize = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 6), Integer32().clone(128)).setMaxAccess("readwrite")
sFlowMaximumDatagramSize = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 7), Integer32().clone(1400)).setMaxAccess("readwrite")
sFlowCollectorAddressType = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 8), InetAddressType()).setMaxAccess("readwrite")
sFlowCollectorAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 9), InetAddress()).setMaxAccess("readwrite")
sFlowCollectorPort = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 10), Integer32().clone(6343)).setMaxAccess("readwrite")
sFlowDatagramVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 4300, 1, 1, 4, 1, 11), Integer32().clone(4)).setMaxAccess("readwrite")
sFlowMIBConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 4300, 1, 2))
sFlowMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 4300, 1, 2, 1))
sFlowMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 4300, 1, 2, 2))

# Augmentions

# Groups

sFlowAgentGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 4300, 1, 2, 1, 1)).setObjects(("SFLOW-MIB", "sFlowDataSource"), ("SFLOW-MIB", "sFlowMaximumDatagramSize"), ("SFLOW-MIB", "sFlowCollectorPort"), ("SFLOW-MIB", "sFlowMaximumHeaderSize"), ("SFLOW-MIB", "sFlowCollectorAddress"), ("SFLOW-MIB", "sFlowOwner"), ("SFLOW-MIB", "sFlowCollectorAddressType"), ("SFLOW-MIB", "sFlowDatagramVersion"), ("SFLOW-MIB", "sFlowTimeout"), ("SFLOW-MIB", "sFlowPacketSamplingRate"), ("SFLOW-MIB", "sFlowCounterSamplingInterval"), ("SFLOW-MIB", "sFlowAgentAddressType"), ("SFLOW-MIB", "sFlowVersion"), ("SFLOW-MIB", "sFlowAgentAddress"), )

# Exports

# Objects
mibBuilder.exportSymbols("SFLOW-MIB", sFlowMIB=sFlowMIB, sFlowAgent=sFlowAgent, sFlowVersion=sFlowVersion, sFlowAgentAddressType=sFlowAgentAddressType, sFlowAgentAddress=sFlowAgentAddress, sFlowTable=sFlowTable, sFlowEntry=sFlowEntry, sFlowDataSource=sFlowDataSource, sFlowOwner=sFlowOwner, sFlowTimeout=sFlowTimeout, sFlowPacketSamplingRate=sFlowPacketSamplingRate, sFlowCounterSamplingInterval=sFlowCounterSamplingInterval, sFlowMaximumHeaderSize=sFlowMaximumHeaderSize, sFlowMaximumDatagramSize=sFlowMaximumDatagramSize, sFlowCollectorAddressType=sFlowCollectorAddressType, sFlowCollectorAddress=sFlowCollectorAddress, sFlowCollectorPort=sFlowCollectorPort, sFlowDatagramVersion=sFlowDatagramVersion, sFlowMIBConformance=sFlowMIBConformance, sFlowMIBGroups=sFlowMIBGroups, sFlowMIBCompliances=sFlowMIBCompliances)

# Groups
mibBuilder.exportSymbols("SFLOW-MIB", sFlowAgentGroup=sFlowAgentGroup)
