# PySNMP SMI module. Autogenerated from smidump -f python TOKENRING-STATION-SR-MIB
# by libsmi2pysnmp-0.0.7-alpha at Thu Nov 16 19:13:42 2006,
# Python version (2, 4, 3, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( ifIndex, ) = mibBuilder.importSymbols("RFC1213-MIB", "ifIndex")
( ModuleCompliance, ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "ObjectGroup")
( Bits, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "mib-2")
( MacAddress, RowStatus, TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "MacAddress", "RowStatus", "TextualConvention")

# Types

class SourceRoute(TextualConvention, OctetString):
    displayHint = "1x:"
    subtypeSpec = OctetString.subtypeSpec+constraint.ValueSizeConstraint(0,30)
    pass


# Objects

dot5SrMIB = ModuleIdentity((1, 3, 6, 1, 2, 1, 42)).setRevisions(("1994-12-16 10:00",))
dot5SrMIBObjects = MibIdentifier((1, 3, 6, 1, 2, 1, 42, 1))
dot5SrRouteTable = MibTable((1, 3, 6, 1, 2, 1, 42, 1, 1))
dot5SrRouteEntry = MibTableRow((1, 3, 6, 1, 2, 1, 42, 1, 1, 1)).setIndexNames((0, "RFC1213-MIB", "ifIndex"), (0, "TOKENRING-STATION-SR-MIB", "dot5SrRouteDestination"))
dot5SrRouteDestination = MibTableColumn((1, 3, 6, 1, 2, 1, 42, 1, 1, 1, 2), MacAddress()).setMaxAccess("noaccess")
dot5SrRouteControl = MibTableColumn((1, 3, 6, 1, 2, 1, 42, 1, 1, 1, 3), OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(2, 2)).setFixedLength()).setMaxAccess("readcreate")
dot5SrRouteDescr = MibTableColumn((1, 3, 6, 1, 2, 1, 42, 1, 1, 1, 4), SourceRoute()).setMaxAccess("readcreate")
dot5SrRouteStatus = MibTableColumn((1, 3, 6, 1, 2, 1, 42, 1, 1, 1, 5), RowStatus()).setMaxAccess("readcreate")
dot5SrConformance = MibIdentifier((1, 3, 6, 1, 2, 1, 42, 2))
dot5SrGroups = MibIdentifier((1, 3, 6, 1, 2, 1, 42, 2, 1))
dot5SrCompliances = MibIdentifier((1, 3, 6, 1, 2, 1, 42, 2, 2))

# Augmentions

# Groups

dot5SrRouteGroup = ObjectGroup((1, 3, 6, 1, 2, 1, 42, 2, 1, 1)).setObjects(("TOKENRING-STATION-SR-MIB", "dot5SrRouteControl"), ("TOKENRING-STATION-SR-MIB", "dot5SrRouteStatus"), ("TOKENRING-STATION-SR-MIB", "dot5SrRouteDescr"), )

# Exports

# Module identity
mibBuilder.exportSymbols("TOKENRING-STATION-SR-MIB", PYSNMP_MODULE_ID=dot5SrMIB)

# Types
mibBuilder.exportSymbols("TOKENRING-STATION-SR-MIB", SourceRoute=SourceRoute)

# Objects
mibBuilder.exportSymbols("TOKENRING-STATION-SR-MIB", dot5SrMIB=dot5SrMIB, dot5SrMIBObjects=dot5SrMIBObjects, dot5SrRouteTable=dot5SrRouteTable, dot5SrRouteEntry=dot5SrRouteEntry, dot5SrRouteDestination=dot5SrRouteDestination, dot5SrRouteControl=dot5SrRouteControl, dot5SrRouteDescr=dot5SrRouteDescr, dot5SrRouteStatus=dot5SrRouteStatus, dot5SrConformance=dot5SrConformance, dot5SrGroups=dot5SrGroups, dot5SrCompliances=dot5SrCompliances)

# Groups
mibBuilder.exportSymbols("TOKENRING-STATION-SR-MIB", dot5SrRouteGroup=dot5SrRouteGroup)
